# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'NewVM.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGridLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSpinBox, QStackedWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(400, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(400, 300))
        Dialog.setMaximumSize(QSize(400, 300))
        Dialog.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.stackedWidget = QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 381, 281))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.gridLayoutWidget = QWidget(self.page)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 381, 281))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.label = QLabel(self.gridLayoutWidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.pushButton_2 = QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)

        self.pushButton_3 = QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)

        self.lineEdit = QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.comboBox = QComboBox(self.gridLayoutWidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")

        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)

        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.gridLayoutWidget_2 = QWidget(self.page_2)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.comboBox_2 = QComboBox(self.gridLayoutWidget_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.gridLayout_2.addWidget(self.comboBox_2, 0, 1, 1, 1)

        self.label_6 = QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)

        self.label_5 = QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)

        self.comboBox_3 = QComboBox(self.gridLayoutWidget_2)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")

        self.gridLayout_2.addWidget(self.comboBox_3, 1, 1, 1, 1)

        self.pushButton_5 = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.gridLayout_2.addWidget(self.pushButton_5, 3, 0, 1, 1)

        self.pushButton_4 = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.gridLayout_2.addWidget(self.pushButton_4, 3, 1, 1, 1)

        self.pushButton_6 = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_6.setObjectName(u"pushButton_6")

        self.gridLayout_2.addWidget(self.pushButton_6, 3, 2, 1, 1)

        self.spinBox = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMaximum(32768)
        self.spinBox.setValue(0)

        self.gridLayout_2.addWidget(self.spinBox, 2, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.gridLayoutWidget_3 = QWidget(self.page_3)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.comboBox_4 = QComboBox(self.gridLayoutWidget_3)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")

        self.gridLayout_3.addWidget(self.comboBox_4, 0, 1, 1, 1)

        self.label_7 = QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)

        self.label_9 = QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)

        self.comboBox_5 = QComboBox(self.gridLayoutWidget_3)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")

        self.gridLayout_3.addWidget(self.comboBox_5, 1, 1, 1, 1)

        self.pushButton_7 = QPushButton(self.gridLayoutWidget_3)
        self.pushButton_7.setObjectName(u"pushButton_7")

        self.gridLayout_3.addWidget(self.pushButton_7, 3, 0, 1, 1)

        self.pushButton_8 = QPushButton(self.gridLayoutWidget_3)
        self.pushButton_8.setObjectName(u"pushButton_8")

        self.gridLayout_3.addWidget(self.pushButton_8, 3, 1, 1, 1)

        self.pushButton_9 = QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9.setObjectName(u"pushButton_9")

        self.gridLayout_3.addWidget(self.pushButton_9, 3, 2, 1, 1)

        self.spinBox_2 = QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setMaximum(32768)

        self.gridLayout_3.addWidget(self.spinBox_2, 2, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.gridLayoutWidget_4 = QWidget(self.page_4)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(0, 10, 381, 271))
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.comboBox_6 = QComboBox(self.gridLayoutWidget_4)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")

        self.gridLayout_4.addWidget(self.comboBox_6, 0, 1, 1, 1)

        self.label_10 = QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)

        self.label_11 = QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)

        self.label_12 = QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)

        self.comboBox_7 = QComboBox(self.gridLayoutWidget_4)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")

        self.gridLayout_4.addWidget(self.comboBox_7, 1, 1, 1, 1)

        self.pushButton_10 = QPushButton(self.gridLayoutWidget_4)
        self.pushButton_10.setObjectName(u"pushButton_10")

        self.gridLayout_4.addWidget(self.pushButton_10, 3, 0, 1, 1)

        self.pushButton_11 = QPushButton(self.gridLayoutWidget_4)
        self.pushButton_11.setObjectName(u"pushButton_11")

        self.gridLayout_4.addWidget(self.pushButton_11, 3, 1, 1, 1)

        self.pushButton_12 = QPushButton(self.gridLayoutWidget_4)
        self.pushButton_12.setObjectName(u"pushButton_12")

        self.gridLayout_4.addWidget(self.pushButton_12, 3, 2, 1, 1)

        self.spinBox_3 = QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setMaximum(32768)

        self.gridLayout_4.addWidget(self.spinBox_3, 2, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_4)
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.gridLayoutWidget_11 = QWidget(self.page_11)
        self.gridLayoutWidget_11.setObjectName(u"gridLayoutWidget_11")
        self.gridLayoutWidget_11.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_11 = QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.comboBox_14 = QComboBox(self.gridLayoutWidget_11)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")

        self.gridLayout_11.addWidget(self.comboBox_14, 0, 1, 1, 1)

        self.label_29 = QLabel(self.gridLayoutWidget_11)
        self.label_29.setObjectName(u"label_29")

        self.gridLayout_11.addWidget(self.label_29, 2, 0, 1, 1)

        self.label_30 = QLabel(self.gridLayoutWidget_11)
        self.label_30.setObjectName(u"label_30")

        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)

        self.label_31 = QLabel(self.gridLayoutWidget_11)
        self.label_31.setObjectName(u"label_31")

        self.gridLayout_11.addWidget(self.label_31, 0, 0, 1, 1)

        self.comboBox_15 = QComboBox(self.gridLayoutWidget_11)
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.setObjectName(u"comboBox_15")

        self.gridLayout_11.addWidget(self.comboBox_15, 1, 1, 1, 1)

        self.pushButton_33 = QPushButton(self.gridLayoutWidget_11)
        self.pushButton_33.setObjectName(u"pushButton_33")

        self.gridLayout_11.addWidget(self.pushButton_33, 3, 0, 1, 1)

        self.pushButton_34 = QPushButton(self.gridLayoutWidget_11)
        self.pushButton_34.setObjectName(u"pushButton_34")

        self.gridLayout_11.addWidget(self.pushButton_34, 3, 1, 1, 1)

        self.pushButton_35 = QPushButton(self.gridLayoutWidget_11)
        self.pushButton_35.setObjectName(u"pushButton_35")

        self.gridLayout_11.addWidget(self.pushButton_35, 3, 2, 1, 1)

        self.spinBox_5 = QSpinBox(self.gridLayoutWidget_11)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setMaximum(32768)

        self.gridLayout_11.addWidget(self.spinBox_5, 2, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.gridLayoutWidget_12 = QWidget(self.page_12)
        self.gridLayoutWidget_12.setObjectName(u"gridLayoutWidget_12")
        self.gridLayoutWidget_12.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_12 = QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.pushButton_38 = QPushButton(self.gridLayoutWidget_12)
        self.pushButton_38.setObjectName(u"pushButton_38")

        self.gridLayout_12.addWidget(self.pushButton_38, 3, 1, 1, 1)

        self.comboBox_20 = QComboBox(self.gridLayoutWidget_12)
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.setObjectName(u"comboBox_20")

        self.gridLayout_12.addWidget(self.comboBox_20, 0, 1, 1, 1)

        self.spinBox_7 = QSpinBox(self.gridLayoutWidget_12)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setMaximum(32768)

        self.gridLayout_12.addWidget(self.spinBox_7, 2, 1, 1, 1)

        self.label_35 = QLabel(self.gridLayoutWidget_12)
        self.label_35.setObjectName(u"label_35")

        self.gridLayout_12.addWidget(self.label_35, 2, 0, 1, 1)

        self.label_22 = QLabel(self.gridLayoutWidget_12)
        self.label_22.setObjectName(u"label_22")

        self.gridLayout_12.addWidget(self.label_22, 0, 0, 1, 1)

        self.pushButton_37 = QPushButton(self.gridLayoutWidget_12)
        self.pushButton_37.setObjectName(u"pushButton_37")

        self.gridLayout_12.addWidget(self.pushButton_37, 3, 0, 1, 1)

        self.pushButton_39 = QPushButton(self.gridLayoutWidget_12)
        self.pushButton_39.setObjectName(u"pushButton_39")

        self.gridLayout_12.addWidget(self.pushButton_39, 3, 2, 1, 1)

        self.stackedWidget.addWidget(self.page_12)
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.gridLayoutWidget_13 = QWidget(self.page_13)
        self.gridLayoutWidget_13.setObjectName(u"gridLayoutWidget_13")
        self.gridLayoutWidget_13.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_13 = QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.pushButton_40 = QPushButton(self.gridLayoutWidget_13)
        self.pushButton_40.setObjectName(u"pushButton_40")

        self.gridLayout_13.addWidget(self.pushButton_40, 3, 1, 1, 1)

        self.comboBox_21 = QComboBox(self.gridLayoutWidget_13)
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.setObjectName(u"comboBox_21")

        self.gridLayout_13.addWidget(self.comboBox_21, 0, 1, 1, 1)

        self.spinBox_8 = QSpinBox(self.gridLayoutWidget_13)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setMaximum(32768)

        self.gridLayout_13.addWidget(self.spinBox_8, 2, 1, 1, 1)

        self.label_36 = QLabel(self.gridLayoutWidget_13)
        self.label_36.setObjectName(u"label_36")

        self.gridLayout_13.addWidget(self.label_36, 2, 0, 1, 1)

        self.label_37 = QLabel(self.gridLayoutWidget_13)
        self.label_37.setObjectName(u"label_37")

        self.gridLayout_13.addWidget(self.label_37, 0, 0, 1, 1)

        self.pushButton_41 = QPushButton(self.gridLayoutWidget_13)
        self.pushButton_41.setObjectName(u"pushButton_41")

        self.gridLayout_13.addWidget(self.pushButton_41, 3, 0, 1, 1)

        self.pushButton_42 = QPushButton(self.gridLayoutWidget_13)
        self.pushButton_42.setObjectName(u"pushButton_42")

        self.gridLayout_13.addWidget(self.pushButton_42, 3, 2, 1, 1)

        self.stackedWidget.addWidget(self.page_13)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.gridLayoutWidget_5 = QWidget(self.page_5)
        self.gridLayoutWidget_5.setObjectName(u"gridLayoutWidget_5")
        self.gridLayoutWidget_5.setGeometry(QRect(0, 0, 381, 281))
        self.gridLayout_5 = QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.pushButton_16 = QPushButton(self.gridLayoutWidget_5)
        self.pushButton_16.setObjectName(u"pushButton_16")

        self.gridLayout_5.addWidget(self.pushButton_16, 4, 0, 1, 1)

        self.lineEdit_6 = QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_6.setObjectName(u"lineEdit_6")

        self.gridLayout_5.addWidget(self.lineEdit_6, 1, 1, 1, 1)

        self.pushButton_15 = QPushButton(self.gridLayoutWidget_5)
        self.pushButton_15.setObjectName(u"pushButton_15")

        self.gridLayout_5.addWidget(self.pushButton_15, 4, 2, 1, 1)

        self.spinBox_4 = QSpinBox(self.gridLayoutWidget_5)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setMaximum(214748368)
        self.spinBox_4.setValue(0)

        self.gridLayout_5.addWidget(self.spinBox_4, 3, 1, 1, 1)

        self.label_13 = QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)

        self.label_15 = QLabel(self.gridLayoutWidget_5)
        self.label_15.setObjectName(u"label_15")

        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)

        self.pushButton_13 = QPushButton(self.gridLayoutWidget_5)
        self.pushButton_13.setObjectName(u"pushButton_13")

        self.gridLayout_5.addWidget(self.pushButton_13, 1, 2, 1, 1)

        self.comboBox_9 = QComboBox(self.gridLayoutWidget_5)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")

        self.gridLayout_5.addWidget(self.comboBox_9, 3, 2, 1, 1)

        self.pushButton_14 = QPushButton(self.gridLayoutWidget_5)
        self.pushButton_14.setObjectName(u"pushButton_14")

        self.gridLayout_5.addWidget(self.pushButton_14, 4, 1, 1, 1)

        self.label_14 = QLabel(self.gridLayoutWidget_5)
        self.label_14.setObjectName(u"label_14")

        self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)

        self.comboBox_8 = QComboBox(self.gridLayoutWidget_5)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")

        self.gridLayout_5.addWidget(self.comboBox_8, 2, 1, 1, 1)

        self.label_20 = QLabel(self.gridLayoutWidget_5)
        self.label_20.setObjectName(u"label_20")

        self.gridLayout_5.addWidget(self.label_20, 0, 0, 1, 1)

        self.comboBox_18 = QComboBox(self.gridLayoutWidget_5)
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.setObjectName(u"comboBox_18")

        self.gridLayout_5.addWidget(self.comboBox_18, 0, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.gridLayoutWidget_6 = QWidget(self.page_6)
        self.gridLayoutWidget_6.setObjectName(u"gridLayoutWidget_6")
        self.gridLayoutWidget_6.setGeometry(QRect(0, 0, 382, 271))
        self.gridLayout_6 = QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.pushButton_17 = QPushButton(self.gridLayoutWidget_6)
        self.pushButton_17.setObjectName(u"pushButton_17")

        self.gridLayout_6.addWidget(self.pushButton_17, 4, 1, 1, 1)

        self.label_16 = QLabel(self.gridLayoutWidget_6)
        self.label_16.setObjectName(u"label_16")

        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)

        self.label_18 = QLabel(self.gridLayoutWidget_6)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)

        self.comboBox_10 = QComboBox(self.gridLayoutWidget_6)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")

        self.gridLayout_6.addWidget(self.comboBox_10, 0, 1, 1, 1)

        self.label_17 = QLabel(self.gridLayoutWidget_6)
        self.label_17.setObjectName(u"label_17")

        self.gridLayout_6.addWidget(self.label_17, 1, 0, 1, 1)

        self.pushButton_18 = QPushButton(self.gridLayoutWidget_6)
        self.pushButton_18.setObjectName(u"pushButton_18")

        self.gridLayout_6.addWidget(self.pushButton_18, 4, 0, 1, 1)

        self.checkBox = QCheckBox(self.gridLayoutWidget_6)
        self.checkBox.setObjectName(u"checkBox")

        self.gridLayout_6.addWidget(self.checkBox, 2, 1, 1, 1)

        self.comboBox_11 = QComboBox(self.gridLayoutWidget_6)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")

        self.gridLayout_6.addWidget(self.comboBox_11, 1, 1, 1, 1)

        self.pushButton_19 = QPushButton(self.gridLayoutWidget_6)
        self.pushButton_19.setObjectName(u"pushButton_19")

        self.gridLayout_6.addWidget(self.pushButton_19, 4, 2, 1, 1)

        self.label_28 = QLabel(self.gridLayoutWidget_6)
        self.label_28.setObjectName(u"label_28")

        self.gridLayout_6.addWidget(self.label_28, 3, 0, 1, 1)

        self.comboBox_13 = QComboBox(self.gridLayoutWidget_6)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")

        self.gridLayout_6.addWidget(self.comboBox_13, 3, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_6)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.gridLayoutWidget_8 = QWidget(self.page_8)
        self.gridLayoutWidget_8.setObjectName(u"gridLayoutWidget_8")
        self.gridLayoutWidget_8.setGeometry(QRect(0, 0, 381, 281))
        self.gridLayout_8 = QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.pushButton_23 = QPushButton(self.gridLayoutWidget_8)
        self.pushButton_23.setObjectName(u"pushButton_23")

        self.gridLayout_8.addWidget(self.pushButton_23, 2, 2, 1, 1)

        self.pushButton_24 = QPushButton(self.gridLayoutWidget_8)
        self.pushButton_24.setObjectName(u"pushButton_24")

        self.gridLayout_8.addWidget(self.pushButton_24, 2, 1, 1, 1)

        self.lineEdit_3 = QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.gridLayout_8.addWidget(self.lineEdit_3, 0, 1, 1, 1)

        self.pushButton_25 = QPushButton(self.gridLayoutWidget_8)
        self.pushButton_25.setObjectName(u"pushButton_25")

        self.gridLayout_8.addWidget(self.pushButton_25, 2, 0, 1, 1)

        self.label_32 = QLabel(self.gridLayoutWidget_8)
        self.label_32.setObjectName(u"label_32")

        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)

        self.lineEdit_8 = QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_8.setObjectName(u"lineEdit_8")

        self.gridLayout_8.addWidget(self.lineEdit_8, 1, 1, 1, 1)

        self.pushButton_36 = QPushButton(self.gridLayoutWidget_8)
        self.pushButton_36.setObjectName(u"pushButton_36")

        self.gridLayout_8.addWidget(self.pushButton_36, 1, 2, 1, 1)

        self.label_19 = QLabel(self.gridLayoutWidget_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setWordWrap(True)

        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.gridLayoutWidget_9 = QWidget(self.page_9)
        self.gridLayoutWidget_9.setObjectName(u"gridLayoutWidget_9")
        self.gridLayoutWidget_9.setGeometry(QRect(0, 0, 381, 271))
        self.gridLayout_9 = QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.comboBox_19 = QComboBox(self.gridLayoutWidget_9)
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.setObjectName(u"comboBox_19")

        self.gridLayout_9.addWidget(self.comboBox_19, 3, 1, 1, 1)

        self.label_21 = QLabel(self.gridLayoutWidget_9)
        self.label_21.setObjectName(u"label_21")

        self.gridLayout_9.addWidget(self.label_21, 3, 0, 1, 1)

        self.comboBox_12 = QComboBox(self.gridLayoutWidget_9)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")

        self.gridLayout_9.addWidget(self.comboBox_12, 0, 1, 1, 1)

        self.pushButton_27 = QPushButton(self.gridLayoutWidget_9)
        self.pushButton_27.setObjectName(u"pushButton_27")

        self.gridLayout_9.addWidget(self.pushButton_27, 4, 1, 1, 1)

        self.pushButton_26 = QPushButton(self.gridLayoutWidget_9)
        self.pushButton_26.setObjectName(u"pushButton_26")

        self.gridLayout_9.addWidget(self.pushButton_26, 4, 2, 1, 1)

        self.comboBox_16 = QComboBox(self.gridLayoutWidget_9)
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.setObjectName(u"comboBox_16")

        self.gridLayout_9.addWidget(self.comboBox_16, 2, 1, 1, 1)

        self.pushButton_28 = QPushButton(self.gridLayoutWidget_9)
        self.pushButton_28.setObjectName(u"pushButton_28")

        self.gridLayout_9.addWidget(self.pushButton_28, 4, 0, 1, 1)

        self.label_33 = QLabel(self.gridLayoutWidget_9)
        self.label_33.setObjectName(u"label_33")

        self.gridLayout_9.addWidget(self.label_33, 1, 0, 1, 1)

        self.label_34 = QLabel(self.gridLayoutWidget_9)
        self.label_34.setObjectName(u"label_34")

        self.gridLayout_9.addWidget(self.label_34, 2, 0, 1, 1)

        self.label_23 = QLabel(self.gridLayoutWidget_9)
        self.label_23.setObjectName(u"label_23")

        self.gridLayout_9.addWidget(self.label_23, 0, 0, 1, 1)

        self.spinBox_6 = QSpinBox(self.gridLayoutWidget_9)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setMaximum(8)

        self.gridLayout_9.addWidget(self.spinBox_6, 1, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.gridLayoutWidget_10 = QWidget(self.page_10)
        self.gridLayoutWidget_10.setObjectName(u"gridLayoutWidget_10")
        self.gridLayoutWidget_10.setGeometry(QRect(0, 0, 383, 281))
        self.gridLayout_10 = QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.pushButton_30 = QPushButton(self.gridLayoutWidget_10)
        self.pushButton_30.setObjectName(u"pushButton_30")

        self.gridLayout_10.addWidget(self.pushButton_30, 4, 1, 1, 1)

        self.label_25 = QLabel(self.gridLayoutWidget_10)
        self.label_25.setObjectName(u"label_25")

        self.gridLayout_10.addWidget(self.label_25, 1, 0, 1, 1)

        self.lineEdit_5 = QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_5.setObjectName(u"lineEdit_5")

        self.gridLayout_10.addWidget(self.lineEdit_5, 1, 1, 1, 1)

        self.lineEdit_4 = QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_4.setObjectName(u"lineEdit_4")

        self.gridLayout_10.addWidget(self.lineEdit_4, 0, 1, 1, 1)

        self.pushButton = QPushButton(self.gridLayoutWidget_10)
        self.pushButton.setObjectName(u"pushButton")

        self.gridLayout_10.addWidget(self.pushButton, 0, 2, 1, 1)

        self.pushButton_32 = QPushButton(self.gridLayoutWidget_10)
        self.pushButton_32.setObjectName(u"pushButton_32")

        self.gridLayout_10.addWidget(self.pushButton_32, 1, 2, 1, 1)

        self.label_24 = QLabel(self.gridLayoutWidget_10)
        self.label_24.setObjectName(u"label_24")

        self.gridLayout_10.addWidget(self.label_24, 0, 0, 1, 1)

        self.pushButton_29 = QPushButton(self.gridLayoutWidget_10)
        self.pushButton_29.setObjectName(u"pushButton_29")

        self.gridLayout_10.addWidget(self.pushButton_29, 4, 2, 1, 1)

        self.pushButton_31 = QPushButton(self.gridLayoutWidget_10)
        self.pushButton_31.setObjectName(u"pushButton_31")

        self.gridLayout_10.addWidget(self.pushButton_31, 4, 0, 1, 1)

        self.label_26 = QLabel(self.gridLayoutWidget_10)
        self.label_26.setObjectName(u"label_26")

        self.gridLayout_10.addWidget(self.label_26, 2, 0, 1, 1)

        self.lineEdit_7 = QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_7.setObjectName(u"lineEdit_7")

        self.gridLayout_10.addWidget(self.lineEdit_7, 2, 1, 1, 1)

        self.label_27 = QLabel(self.gridLayoutWidget_10)
        self.label_27.setObjectName(u"label_27")

        self.gridLayout_10.addWidget(self.label_27, 3, 1, 1, 1)

        self.stackedWidget.addWidget(self.page_10)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.gridLayoutWidget_7 = QWidget(self.page_7)
        self.gridLayoutWidget_7.setObjectName(u"gridLayoutWidget_7")
        self.gridLayoutWidget_7.setGeometry(QRect(0, 0, 381, 281))
        self.gridLayout_7 = QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.pushButton_20 = QPushButton(self.gridLayoutWidget_7)
        self.pushButton_20.setObjectName(u"pushButton_20")

        self.gridLayout_7.addWidget(self.pushButton_20, 4, 1, 1, 1)

        self.pushButton_21 = QPushButton(self.gridLayoutWidget_7)
        self.pushButton_21.setObjectName(u"pushButton_21")

        self.gridLayout_7.addWidget(self.pushButton_21, 5, 1, 1, 1)

        self.checkBox_2 = QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_2.setObjectName(u"checkBox_2")

        self.gridLayout_7.addWidget(self.checkBox_2, 1, 0, 1, 1)

        self.pushButton_22 = QPushButton(self.gridLayoutWidget_7)
        self.pushButton_22.setObjectName(u"pushButton_22")

        self.gridLayout_7.addWidget(self.pushButton_22, 4, 0, 1, 1)

        self.label_2 = QLabel(self.gridLayoutWidget_7)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout_7.addWidget(self.label_2, 3, 0, 1, 1)

        self.lineEdit_2 = QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.gridLayout_7.addWidget(self.lineEdit_2, 3, 1, 1, 1)

        self.comboBox_17 = QComboBox(self.gridLayoutWidget_7)
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.setObjectName(u"comboBox_17")

        self.gridLayout_7.addWidget(self.comboBox_17, 2, 1, 1, 1)

        self.checkBox_3 = QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_3.setObjectName(u"checkBox_3")

        self.gridLayout_7.addWidget(self.checkBox_3, 2, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_7)

        self.retranslateUi(Dialog)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Architecture", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Name", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"i386", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"x86_64", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"mips64el", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"mipsel", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Dialog", u"ppc", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("Dialog", u"ppc64", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("Dialog", u"aarch64", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("Dialog", u"arm", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("Dialog", u"sparc", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("Dialog", u"sparc64", None))

        self.comboBox.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please choose an architecture", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Dialog", u"microvm", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("Dialog", u"pc", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("Dialog", u"q35", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("Dialog", u"isapc", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("Dialog", u"none", None))

        self.comboBox_2.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a machine", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"CPU", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("Dialog", u"486", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("Dialog", u"Broadwell", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("Dialog", u"Cascadelake-Server", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("Dialog", u"Conroe", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("Dialog", u"Cooperlake", None))
        self.comboBox_3.setItemText(6, QCoreApplication.translate("Dialog", u"Denverton", None))
        self.comboBox_3.setItemText(7, QCoreApplication.translate("Dialog", u"Dhyana", None))
        self.comboBox_3.setItemText(8, QCoreApplication.translate("Dialog", u"EPYC", None))
        self.comboBox_3.setItemText(9, QCoreApplication.translate("Dialog", u"EPYC-Milan", None))
        self.comboBox_3.setItemText(10, QCoreApplication.translate("Dialog", u"EPYC-Rome", None))
        self.comboBox_3.setItemText(11, QCoreApplication.translate("Dialog", u"Haswell", None))
        self.comboBox_3.setItemText(12, QCoreApplication.translate("Dialog", u"Icelake-Client (depreciated)", None))
        self.comboBox_3.setItemText(13, QCoreApplication.translate("Dialog", u"Icelake-Server", None))
        self.comboBox_3.setItemText(14, QCoreApplication.translate("Dialog", u"IvyBridge", None))
        self.comboBox_3.setItemText(15, QCoreApplication.translate("Dialog", u"KnightsMill", None))
        self.comboBox_3.setItemText(16, QCoreApplication.translate("Dialog", u"Nehalem", None))
        self.comboBox_3.setItemText(17, QCoreApplication.translate("Dialog", u"Opteron_G1", None))
        self.comboBox_3.setItemText(18, QCoreApplication.translate("Dialog", u"Opteron_G2", None))
        self.comboBox_3.setItemText(19, QCoreApplication.translate("Dialog", u"Opteron_G3", None))
        self.comboBox_3.setItemText(20, QCoreApplication.translate("Dialog", u"Opteron_G4", None))
        self.comboBox_3.setItemText(21, QCoreApplication.translate("Dialog", u"Opteron_G5", None))
        self.comboBox_3.setItemText(22, QCoreApplication.translate("Dialog", u"Penryn", None))
        self.comboBox_3.setItemText(23, QCoreApplication.translate("Dialog", u"SandyBridge", None))
        self.comboBox_3.setItemText(24, QCoreApplication.translate("Dialog", u"Skylake-Client", None))
        self.comboBox_3.setItemText(25, QCoreApplication.translate("Dialog", u"Skylake-Server", None))
        self.comboBox_3.setItemText(26, QCoreApplication.translate("Dialog", u"Snowridge", None))
        self.comboBox_3.setItemText(27, QCoreApplication.translate("Dialog", u"Westmere", None))
        self.comboBox_3.setItemText(28, QCoreApplication.translate("Dialog", u"athlon", None))
        self.comboBox_3.setItemText(29, QCoreApplication.translate("Dialog", u"core2duo", None))
        self.comboBox_3.setItemText(30, QCoreApplication.translate("Dialog", u"coreduo", None))
        self.comboBox_3.setItemText(31, QCoreApplication.translate("Dialog", u"kvm32", None))
        self.comboBox_3.setItemText(32, QCoreApplication.translate("Dialog", u"kvm64", None))
        self.comboBox_3.setItemText(33, QCoreApplication.translate("Dialog", u"n270", None))
        self.comboBox_3.setItemText(34, QCoreApplication.translate("Dialog", u"pentium", None))
        self.comboBox_3.setItemText(35, QCoreApplication.translate("Dialog", u"pentium2", None))
        self.comboBox_3.setItemText(36, QCoreApplication.translate("Dialog", u"pentium3", None))
        self.comboBox_3.setItemText(37, QCoreApplication.translate("Dialog", u"phenom", None))
        self.comboBox_3.setItemText(38, QCoreApplication.translate("Dialog", u"qemu32", None))
        self.comboBox_3.setItemText(39, QCoreApplication.translate("Dialog", u"qemu64", None))
        self.comboBox_3.setItemText(40, QCoreApplication.translate("Dialog", u"base", None))
        self.comboBox_3.setItemText(41, QCoreApplication.translate("Dialog", u"max", None))
        self.comboBox_3.setItemText(42, QCoreApplication.translate("Dialog", u"host", None))

        self.comboBox_3.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a processor", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("Dialog", u"40p", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("Dialog", u"bamboo", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("Dialog", u"g3beige", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("Dialog", u"mac99", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("Dialog", u"mac99,via=pmu", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("Dialog", u"mac99,via=pmu-adb", None))
        self.comboBox_4.setItemText(7, QCoreApplication.translate("Dialog", u"none", None))
        self.comboBox_4.setItemText(8, QCoreApplication.translate("Dialog", u"mpc8544ds", None))
        self.comboBox_4.setItemText(9, QCoreApplication.translate("Dialog", u"pegasos2", None))
        self.comboBox_4.setItemText(10, QCoreApplication.translate("Dialog", u"ppce500", None))
        self.comboBox_4.setItemText(11, QCoreApplication.translate("Dialog", u"ref405ep", None))
        self.comboBox_4.setItemText(12, QCoreApplication.translate("Dialog", u"sam460ex", None))
        self.comboBox_4.setItemText(13, QCoreApplication.translate("Dialog", u"taihu", None))
        self.comboBox_4.setItemText(14, QCoreApplication.translate("Dialog", u"virtex-ml507", None))

        self.comboBox_4.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a machine", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"CPU", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("Dialog", u"603", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("Dialog", u"604", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("Dialog", u"603e", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("Dialog", u"603p", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("Dialog", u"603e7v", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("Dialog", u"603e7v1", None))
        self.comboBox_5.setItemText(7, QCoreApplication.translate("Dialog", u"603e7", None))
        self.comboBox_5.setItemText(8, QCoreApplication.translate("Dialog", u"603e7v2", None))
        self.comboBox_5.setItemText(9, QCoreApplication.translate("Dialog", u"603e7t", None))
        self.comboBox_5.setItemText(10, QCoreApplication.translate("Dialog", u"750", None))
        self.comboBox_5.setItemText(11, QCoreApplication.translate("Dialog", u"740", None))
        self.comboBox_5.setItemText(12, QCoreApplication.translate("Dialog", u"740e", None))
        self.comboBox_5.setItemText(13, QCoreApplication.translate("Dialog", u"750e", None))
        self.comboBox_5.setItemText(14, QCoreApplication.translate("Dialog", u"750cx", None))
        self.comboBox_5.setItemText(15, QCoreApplication.translate("Dialog", u"745", None))
        self.comboBox_5.setItemText(16, QCoreApplication.translate("Dialog", u"755", None))
        self.comboBox_5.setItemText(17, QCoreApplication.translate("Dialog", u"750cxe", None))
        self.comboBox_5.setItemText(18, QCoreApplication.translate("Dialog", u"750cxr", None))
        self.comboBox_5.setItemText(19, QCoreApplication.translate("Dialog", u"750cl", None))
        self.comboBox_5.setItemText(20, QCoreApplication.translate("Dialog", u"750l", None))
        self.comboBox_5.setItemText(21, QCoreApplication.translate("Dialog", u"604e", None))
        self.comboBox_5.setItemText(22, QCoreApplication.translate("Dialog", u"604r", None))
        self.comboBox_5.setItemText(23, QCoreApplication.translate("Dialog", u"7400", None))
        self.comboBox_5.setItemText(24, QCoreApplication.translate("Dialog", u"g2", None))
        self.comboBox_5.setItemText(25, QCoreApplication.translate("Dialog", u"mpc603", None))
        self.comboBox_5.setItemText(26, QCoreApplication.translate("Dialog", u"g2hip3", None))
        self.comboBox_5.setItemText(27, QCoreApplication.translate("Dialog", u"mpc8343", None))
        self.comboBox_5.setItemText(28, QCoreApplication.translate("Dialog", u"mpc8349a", None))
        self.comboBox_5.setItemText(29, QCoreApplication.translate("Dialog", u"mpc8347a", None))
        self.comboBox_5.setItemText(30, QCoreApplication.translate("Dialog", u"e300c1", None))
        self.comboBox_5.setItemText(31, QCoreApplication.translate("Dialog", u"mpc8347e", None))
        self.comboBox_5.setItemText(32, QCoreApplication.translate("Dialog", u"mpc8347", None))
        self.comboBox_5.setItemText(33, QCoreApplication.translate("Dialog", u"mpc8343a", None))
        self.comboBox_5.setItemText(34, QCoreApplication.translate("Dialog", u"mpc8347ea", None))
        self.comboBox_5.setItemText(35, QCoreApplication.translate("Dialog", u"mpc8347ap", None))
        self.comboBox_5.setItemText(36, QCoreApplication.translate("Dialog", u"mpc8349ea", None))
        self.comboBox_5.setItemText(37, QCoreApplication.translate("Dialog", u"mpc8343e", None))
        self.comboBox_5.setItemText(38, QCoreApplication.translate("Dialog", u"e300", None))
        self.comboBox_5.setItemText(39, QCoreApplication.translate("Dialog", u"mpc8379e", None))
        self.comboBox_5.setItemText(40, QCoreApplication.translate("Dialog", u"mpc8377e", None))
        self.comboBox_5.setItemText(41, QCoreApplication.translate("Dialog", u"mpc8377", None))
        self.comboBox_5.setItemText(42, QCoreApplication.translate("Dialog", u"mpc8378", None))
        self.comboBox_5.setItemText(43, QCoreApplication.translate("Dialog", u"mpc8378e", None))
        self.comboBox_5.setItemText(44, QCoreApplication.translate("Dialog", u"mpc8379", None))
        self.comboBox_5.setItemText(45, QCoreApplication.translate("Dialog", u"740p", None))
        self.comboBox_5.setItemText(46, QCoreApplication.translate("Dialog", u"750p", None))
        self.comboBox_5.setItemText(47, QCoreApplication.translate("Dialog", u"460ex", None))
        self.comboBox_5.setItemText(48, QCoreApplication.translate("Dialog", u"x2vp7", None))
        self.comboBox_5.setItemText(49, QCoreApplication.translate("Dialog", u"x2vp20", None))
        self.comboBox_5.setItemText(50, QCoreApplication.translate("Dialog", u"405gp", None))
        self.comboBox_5.setItemText(51, QCoreApplication.translate("Dialog", u"405gpe", None))
        self.comboBox_5.setItemText(52, QCoreApplication.translate("Dialog", u"405", None))
        self.comboBox_5.setItemText(53, QCoreApplication.translate("Dialog", u"440ep", None))
        self.comboBox_5.setItemText(54, QCoreApplication.translate("Dialog", u"750fx", None))
        self.comboBox_5.setItemText(55, QCoreApplication.translate("Dialog", u"750gx", None))
        self.comboBox_5.setItemText(56, QCoreApplication.translate("Dialog", u"7450", None))
        self.comboBox_5.setItemText(57, QCoreApplication.translate("Dialog", u"7451", None))
        self.comboBox_5.setItemText(58, QCoreApplication.translate("Dialog", u"7441", None))
        self.comboBox_5.setItemText(59, QCoreApplication.translate("Dialog", u"7455", None))
        self.comboBox_5.setItemText(60, QCoreApplication.translate("Dialog", u"7445", None))
        self.comboBox_5.setItemText(61, QCoreApplication.translate("Dialog", u"7447", None))
        self.comboBox_5.setItemText(62, QCoreApplication.translate("Dialog", u"7457", None))
        self.comboBox_5.setItemText(63, QCoreApplication.translate("Dialog", u"7457a", None))
        self.comboBox_5.setItemText(64, QCoreApplication.translate("Dialog", u"7447a", None))
        self.comboBox_5.setItemText(65, QCoreApplication.translate("Dialog", u"7448", None))
        self.comboBox_5.setItemText(66, QCoreApplication.translate("Dialog", u"7410", None))
        self.comboBox_5.setItemText(67, QCoreApplication.translate("Dialog", u"mpc8541", None))
        self.comboBox_5.setItemText(68, QCoreApplication.translate("Dialog", u"mpc8541e", None))
        self.comboBox_5.setItemText(69, QCoreApplication.translate("Dialog", u"mpc8540", None))
        self.comboBox_5.setItemText(70, QCoreApplication.translate("Dialog", u"e500v1", None))
        self.comboBox_5.setItemText(71, QCoreApplication.translate("Dialog", u"mpc8555", None))
        self.comboBox_5.setItemText(72, QCoreApplication.translate("Dialog", u"mpc8555e", None))
        self.comboBox_5.setItemText(73, QCoreApplication.translate("Dialog", u"mpc8545e", None))
        self.comboBox_5.setItemText(74, QCoreApplication.translate("Dialog", u"mpc8560", None))

        self.comboBox_5.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a processor", None))
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_8.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_9.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("Dialog", u"boston", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("Dialog", u"fuloong2e", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("Dialog", u"loongson3-virt", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("Dialog", u"magnum", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("Dialog", u"malta", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("Dialog", u"mipssim", None))
        self.comboBox_6.setItemText(7, QCoreApplication.translate("Dialog", u"none", None))
        self.comboBox_6.setItemText(8, QCoreApplication.translate("Dialog", u"pica61", None))

        self.comboBox_6.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a machine", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"CPU", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("Dialog", u"4Kc", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("Dialog", u"4Km", None))
        self.comboBox_7.setItemText(3, QCoreApplication.translate("Dialog", u"4KEcR1", None))
        self.comboBox_7.setItemText(4, QCoreApplication.translate("Dialog", u"4KEmR1", None))
        self.comboBox_7.setItemText(5, QCoreApplication.translate("Dialog", u"4KEc", None))
        self.comboBox_7.setItemText(6, QCoreApplication.translate("Dialog", u"4KEm", None))
        self.comboBox_7.setItemText(7, QCoreApplication.translate("Dialog", u"24Kc", None))
        self.comboBox_7.setItemText(8, QCoreApplication.translate("Dialog", u"24KEc", None))
        self.comboBox_7.setItemText(9, QCoreApplication.translate("Dialog", u"24Kf", None))
        self.comboBox_7.setItemText(10, QCoreApplication.translate("Dialog", u"34Kf", None))
        self.comboBox_7.setItemText(11, QCoreApplication.translate("Dialog", u"74Kf", None))
        self.comboBox_7.setItemText(12, QCoreApplication.translate("Dialog", u"M14K", None))
        self.comboBox_7.setItemText(13, QCoreApplication.translate("Dialog", u"M14Kc", None))
        self.comboBox_7.setItemText(14, QCoreApplication.translate("Dialog", u"P5600", None))
        self.comboBox_7.setItemText(15, QCoreApplication.translate("Dialog", u"mips32r6-generic", None))
        self.comboBox_7.setItemText(16, QCoreApplication.translate("Dialog", u"I7200", None))
        self.comboBox_7.setItemText(17, QCoreApplication.translate("Dialog", u"R4000", None))
        self.comboBox_7.setItemText(18, QCoreApplication.translate("Dialog", u"VR5432", None))
        self.comboBox_7.setItemText(19, QCoreApplication.translate("Dialog", u"5Kc", None))
        self.comboBox_7.setItemText(20, QCoreApplication.translate("Dialog", u"5Kf", None))
        self.comboBox_7.setItemText(21, QCoreApplication.translate("Dialog", u"20Kc", None))
        self.comboBox_7.setItemText(22, QCoreApplication.translate("Dialog", u"MIPS64R2-generic", None))
        self.comboBox_7.setItemText(23, QCoreApplication.translate("Dialog", u"5KEc", None))
        self.comboBox_7.setItemText(24, QCoreApplication.translate("Dialog", u"5KEf", None))
        self.comboBox_7.setItemText(25, QCoreApplication.translate("Dialog", u"I6400", None))
        self.comboBox_7.setItemText(26, QCoreApplication.translate("Dialog", u"I6500", None))
        self.comboBox_7.setItemText(27, QCoreApplication.translate("Dialog", u"Loongson-2E", None))
        self.comboBox_7.setItemText(28, QCoreApplication.translate("Dialog", u"Loongson-2F", None))
        self.comboBox_7.setItemText(29, QCoreApplication.translate("Dialog", u"Loongson-3A1000", None))
        self.comboBox_7.setItemText(30, QCoreApplication.translate("Dialog", u"Loongson-3A4000", None))
        self.comboBox_7.setItemText(31, QCoreApplication.translate("Dialog", u"mips64dspr2", None))

        self.comboBox_7.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a processor", None))
        self.pushButton_10.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_12.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.comboBox_14.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_14.setItemText(1, QCoreApplication.translate("Dialog", u"virt", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("Dialog", u"akita", None))
        self.comboBox_14.setItemText(3, QCoreApplication.translate("Dialog", u"ast2500-evb", None))
        self.comboBox_14.setItemText(4, QCoreApplication.translate("Dialog", u"borzoi", None))
        self.comboBox_14.setItemText(5, QCoreApplication.translate("Dialog", u"canon-a1100", None))
        self.comboBox_14.setItemText(6, QCoreApplication.translate("Dialog", u"cheetah", None))
        self.comboBox_14.setItemText(7, QCoreApplication.translate("Dialog", u"collie", None))
        self.comboBox_14.setItemText(8, QCoreApplication.translate("Dialog", u"connex", None))
        self.comboBox_14.setItemText(9, QCoreApplication.translate("Dialog", u"cubieboard", None))
        self.comboBox_14.setItemText(10, QCoreApplication.translate("Dialog", u"highbank", None))
        self.comboBox_14.setItemText(11, QCoreApplication.translate("Dialog", u"imx25-pdk", None))
        self.comboBox_14.setItemText(12, QCoreApplication.translate("Dialog", u"integratorcp", None))
        self.comboBox_14.setItemText(13, QCoreApplication.translate("Dialog", u"kzm", None))
        self.comboBox_14.setItemText(14, QCoreApplication.translate("Dialog", u"lm3s6965evb", None))
        self.comboBox_14.setItemText(15, QCoreApplication.translate("Dialog", u"lm3s811evb", None))
        self.comboBox_14.setItemText(16, QCoreApplication.translate("Dialog", u"none", None))
        self.comboBox_14.setItemText(17, QCoreApplication.translate("Dialog", u"raspi2", None))

        self.comboBox_14.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a machine", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"CPU", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.comboBox_15.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_15.setItemText(1, QCoreApplication.translate("Dialog", u"cortex-a57", None))
        self.comboBox_15.setItemText(2, QCoreApplication.translate("Dialog", u"cortex-a15", None))
        self.comboBox_15.setItemText(3, QCoreApplication.translate("Dialog", u"cortex-a9", None))
        self.comboBox_15.setItemText(4, QCoreApplication.translate("Dialog", u"a64fx", None))
        self.comboBox_15.setItemText(5, QCoreApplication.translate("Dialog", u"arm1026", None))
        self.comboBox_15.setItemText(6, QCoreApplication.translate("Dialog", u"arm1136", None))
        self.comboBox_15.setItemText(7, QCoreApplication.translate("Dialog", u"arm1136-r2", None))
        self.comboBox_15.setItemText(8, QCoreApplication.translate("Dialog", u"arm1176", None))
        self.comboBox_15.setItemText(9, QCoreApplication.translate("Dialog", u"arm11mpcore", None))
        self.comboBox_15.setItemText(10, QCoreApplication.translate("Dialog", u"arm926", None))
        self.comboBox_15.setItemText(11, QCoreApplication.translate("Dialog", u"arm946", None))
        self.comboBox_15.setItemText(12, QCoreApplication.translate("Dialog", u"cortex-a7", None))
        self.comboBox_15.setItemText(13, QCoreApplication.translate("Dialog", u"cortex-a72", None))
        self.comboBox_15.setItemText(14, QCoreApplication.translate("Dialog", u"cortex-a8", None))
        self.comboBox_15.setItemText(15, QCoreApplication.translate("Dialog", u"cortex-m0", None))
        self.comboBox_15.setItemText(16, QCoreApplication.translate("Dialog", u"cortex-m3", None))
        self.comboBox_15.setItemText(17, QCoreApplication.translate("Dialog", u"cortex-m33", None))
        self.comboBox_15.setItemText(18, QCoreApplication.translate("Dialog", u"cortex-m4", None))
        self.comboBox_15.setItemText(19, QCoreApplication.translate("Dialog", u"cortex-m55", None))
        self.comboBox_15.setItemText(20, QCoreApplication.translate("Dialog", u"cortex-m7", None))
        self.comboBox_15.setItemText(21, QCoreApplication.translate("Dialog", u"cortex-r5", None))
        self.comboBox_15.setItemText(22, QCoreApplication.translate("Dialog", u"cortex-r5f", None))
        self.comboBox_15.setItemText(23, QCoreApplication.translate("Dialog", u"max", None))
        self.comboBox_15.setItemText(24, QCoreApplication.translate("Dialog", u"pxa250", None))
        self.comboBox_15.setItemText(25, QCoreApplication.translate("Dialog", u"pxa255", None))
        self.comboBox_15.setItemText(26, QCoreApplication.translate("Dialog", u"pxa260", None))
        self.comboBox_15.setItemText(27, QCoreApplication.translate("Dialog", u"pxa261", None))
        self.comboBox_15.setItemText(28, QCoreApplication.translate("Dialog", u"pxa262", None))
        self.comboBox_15.setItemText(29, QCoreApplication.translate("Dialog", u"pxa270", None))
        self.comboBox_15.setItemText(30, QCoreApplication.translate("Dialog", u"sa1100", None))
        self.comboBox_15.setItemText(31, QCoreApplication.translate("Dialog", u"sa1110", None))
        self.comboBox_15.setItemText(32, QCoreApplication.translate("Dialog", u"ti925t", None))

        self.comboBox_15.setPlaceholderText(QCoreApplication.translate("Dialog", u"Please select a processor", None))
        self.pushButton_33.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_34.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_35.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_38.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.comboBox_20.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_20.setItemText(1, QCoreApplication.translate("Dialog", u"SPARCClassic", None))
        self.comboBox_20.setItemText(2, QCoreApplication.translate("Dialog", u"SPARCbook", None))
        self.comboBox_20.setItemText(3, QCoreApplication.translate("Dialog", u"SS-10", None))
        self.comboBox_20.setItemText(4, QCoreApplication.translate("Dialog", u"SS-20", None))
        self.comboBox_20.setItemText(5, QCoreApplication.translate("Dialog", u"SS-4", None))
        self.comboBox_20.setItemText(6, QCoreApplication.translate("Dialog", u"SS-5", None))
        self.comboBox_20.setItemText(7, QCoreApplication.translate("Dialog", u"SS-600MP", None))
        self.comboBox_20.setItemText(8, QCoreApplication.translate("Dialog", u"Voyager", None))
        self.comboBox_20.setItemText(9, QCoreApplication.translate("Dialog", u"leon3_generic", None))
        self.comboBox_20.setItemText(10, QCoreApplication.translate("Dialog", u"none", None))

        self.label_35.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.pushButton_37.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_39.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_40.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.comboBox_21.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_21.setItemText(1, QCoreApplication.translate("Dialog", u"niagara", None))
        self.comboBox_21.setItemText(2, QCoreApplication.translate("Dialog", u"sun4u", None))
        self.comboBox_21.setItemText(3, QCoreApplication.translate("Dialog", u"sun4v", None))
        self.comboBox_21.setItemText(4, QCoreApplication.translate("Dialog", u"none", None))

        self.label_36.setText(QCoreApplication.translate("Dialog", u"RAM in MB", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"Machine", None))
        self.pushButton_41.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_42.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"VHD path", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Maximum size", None))
        self.pushButton_13.setText(QCoreApplication.translate("Dialog", u"Browse", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("Dialog", u"KB", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("Dialog", u"MB", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("Dialog", u"GB", None))

        self.pushButton_14.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"VHD file format", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("Dialog", u"qcow2", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("Dialog", u"qcow", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("Dialog", u"raw", None))
        self.comboBox_8.setItemText(3, QCoreApplication.translate("Dialog", u"vdi", None))
        self.comboBox_8.setItemText(4, QCoreApplication.translate("Dialog", u"vmdk", None))
        self.comboBox_8.setItemText(5, QCoreApplication.translate("Dialog", u"vpc", None))
        self.comboBox_8.setItemText(6, QCoreApplication.translate("Dialog", u"vhdx", None))
        self.comboBox_8.setItemText(7, QCoreApplication.translate("Dialog", u"parallels", None))
        self.comboBox_8.setItemText(8, QCoreApplication.translate("Dialog", u"file", None))

        self.comboBox_8.setPlaceholderText(QCoreApplication.translate("Dialog", u"(Please select a file format)", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"VHD usage", None))
        self.comboBox_18.setItemText(0, QCoreApplication.translate("Dialog", u"Create a new virtual hard drive", None))
        self.comboBox_18.setItemText(1, QCoreApplication.translate("Dialog", u"Add an existing virtual hard drive", None))
        self.comboBox_18.setItemText(2, QCoreApplication.translate("Dialog", u"Don't add a virtual hard drive", None))

        self.pushButton_17.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"VGA", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"USB Device Tablet", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("Dialog", u"Let QEMU decide", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("Dialog", u"none", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("Dialog", u"std", None))
        self.comboBox_10.setItemText(3, QCoreApplication.translate("Dialog", u"vmware", None))
        self.comboBox_10.setItemText(4, QCoreApplication.translate("Dialog", u"xenfb", None))
        self.comboBox_10.setItemText(5, QCoreApplication.translate("Dialog", u"qxl", None))
        self.comboBox_10.setItemText(6, QCoreApplication.translate("Dialog", u"virtio", None))
        self.comboBox_10.setItemText(7, QCoreApplication.translate("Dialog", u"virtio-gpu-pci", None))
        self.comboBox_10.setItemText(8, QCoreApplication.translate("Dialog", u"cirrus", None))
        self.comboBox_10.setItemText(9, QCoreApplication.translate("Dialog", u"cg3", None))

        self.comboBox_10.setPlaceholderText(QCoreApplication.translate("Dialog", u"(Please select a graphics adapter)", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Network", None))
        self.pushButton_18.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Yes, I want it (depreciated)", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("Dialog", u"e1000", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("Dialog", u"e1000-82544gc", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("Dialog", u"e1000-82545em", None))
        self.comboBox_11.setItemText(3, QCoreApplication.translate("Dialog", u"e1000e", None))
        self.comboBox_11.setItemText(4, QCoreApplication.translate("Dialog", u"i82550", None))
        self.comboBox_11.setItemText(5, QCoreApplication.translate("Dialog", u"i82551", None))
        self.comboBox_11.setItemText(6, QCoreApplication.translate("Dialog", u"i82557a", None))
        self.comboBox_11.setItemText(7, QCoreApplication.translate("Dialog", u"i82557b", None))
        self.comboBox_11.setItemText(8, QCoreApplication.translate("Dialog", u"i82557c", None))
        self.comboBox_11.setItemText(9, QCoreApplication.translate("Dialog", u"i82558a", None))
        self.comboBox_11.setItemText(10, QCoreApplication.translate("Dialog", u"i82558b", None))
        self.comboBox_11.setItemText(11, QCoreApplication.translate("Dialog", u"i82559a", None))
        self.comboBox_11.setItemText(12, QCoreApplication.translate("Dialog", u"i82559b", None))
        self.comboBox_11.setItemText(13, QCoreApplication.translate("Dialog", u"i82559c", None))
        self.comboBox_11.setItemText(14, QCoreApplication.translate("Dialog", u"i82559er", None))
        self.comboBox_11.setItemText(15, QCoreApplication.translate("Dialog", u"i82562", None))
        self.comboBox_11.setItemText(16, QCoreApplication.translate("Dialog", u"i82801", None))
        self.comboBox_11.setItemText(17, QCoreApplication.translate("Dialog", u"ne2k_pci", None))
        self.comboBox_11.setItemText(18, QCoreApplication.translate("Dialog", u"pcnet", None))
        self.comboBox_11.setItemText(19, QCoreApplication.translate("Dialog", u"rtl8139", None))
        self.comboBox_11.setItemText(20, QCoreApplication.translate("Dialog", u"tulip", None))
        self.comboBox_11.setItemText(21, QCoreApplication.translate("Dialog", u"virtio-net", None))
        self.comboBox_11.setItemText(22, QCoreApplication.translate("Dialog", u"virtio-net-device", None))
        self.comboBox_11.setItemText(23, QCoreApplication.translate("Dialog", u"virtio-net-pci", None))
        self.comboBox_11.setItemText(24, QCoreApplication.translate("Dialog", u"virtio-net-pci-non-transitional", None))
        self.comboBox_11.setItemText(25, QCoreApplication.translate("Dialog", u"virtio-net-pci-transitional", None))
        self.comboBox_11.setItemText(26, QCoreApplication.translate("Dialog", u"vmxnet3", None))
        self.comboBox_11.setItemText(27, QCoreApplication.translate("Dialog", u"dp83932", None))
        self.comboBox_11.setItemText(28, QCoreApplication.translate("Dialog", u"lance", None))
        self.comboBox_11.setItemText(29, QCoreApplication.translate("Dialog", u"none", None))

        self.comboBox_11.setPlaceholderText(QCoreApplication.translate("Dialog", u"(Please select a network adapter)", None))
        self.pushButton_19.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Mouse", None))
        self.comboBox_13.setItemText(0, QCoreApplication.translate("Dialog", u"PS/2 Mouse", None))
        self.comboBox_13.setItemText(1, QCoreApplication.translate("Dialog", u"USB Mouse", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("Dialog", u"USB Tablet Device", None))

        self.pushButton_23.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_24.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_25.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"External BIOS file", None))
        self.pushButton_36.setText(QCoreApplication.translate("Dialog", u"Browse", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Location of external\n"
"BIOS file (Leave\n"
"empty to use the\n"
"default BIOS)", None))
        self.comboBox_19.setItemText(0, QCoreApplication.translate("Dialog", u"en-us", None))
        self.comboBox_19.setItemText(1, QCoreApplication.translate("Dialog", u"en-gb", None))
        self.comboBox_19.setItemText(2, QCoreApplication.translate("Dialog", u"de", None))
        self.comboBox_19.setItemText(3, QCoreApplication.translate("Dialog", u"fr", None))
        self.comboBox_19.setItemText(4, QCoreApplication.translate("Dialog", u"ja", None))
        self.comboBox_19.setItemText(5, QCoreApplication.translate("Dialog", u"ru", None))
        self.comboBox_19.setItemText(6, QCoreApplication.translate("Dialog", u"pl", None))
        self.comboBox_19.setItemText(7, QCoreApplication.translate("Dialog", u"is", None))
        self.comboBox_19.setItemText(8, QCoreApplication.translate("Dialog", u"es", None))
        self.comboBox_19.setItemText(9, QCoreApplication.translate("Dialog", u"pt", None))
        self.comboBox_19.setItemText(10, QCoreApplication.translate("Dialog", u"fi", None))
        self.comboBox_19.setItemText(11, QCoreApplication.translate("Dialog", u"it", None))

        self.label_21.setText(QCoreApplication.translate("Dialog", u"Keyboard layout", None))
        self.comboBox_12.setItemText(0, QCoreApplication.translate("Dialog", u"none", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("Dialog", u"sb16", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("Dialog", u"pcspk", None))
        self.comboBox_12.setItemText(3, QCoreApplication.translate("Dialog", u"intel-hda", None))
        self.comboBox_12.setItemText(4, QCoreApplication.translate("Dialog", u"gus", None))
        self.comboBox_12.setItemText(5, QCoreApplication.translate("Dialog", u"ES1370", None))
        self.comboBox_12.setItemText(6, QCoreApplication.translate("Dialog", u"cs4231a", None))
        self.comboBox_12.setItemText(7, QCoreApplication.translate("Dialog", u"adlib", None))
        self.comboBox_12.setItemText(8, QCoreApplication.translate("Dialog", u"AC97", None))

        self.pushButton_27.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.pushButton_26.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.comboBox_16.setItemText(0, QCoreApplication.translate("Dialog", u"PS/2 Keyboard", None))
        self.comboBox_16.setItemText(1, QCoreApplication.translate("Dialog", u"USB Keyboard", None))

        self.pushButton_28.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"CPU cores", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Keyboard", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Sound card", None))
        self.pushButton_30.setText(QCoreApplication.translate("Dialog", u"Next >", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Linux initrd image", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Browse", None))
        self.pushButton_32.setText(QCoreApplication.translate("Dialog", u"Browse", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Linux kernel", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.pushButton_31.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"Linux cmd args", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Leave empty if these aren't necessary", None))
        self.pushButton_20.setText(QCoreApplication.translate("Dialog", u"Finish", None))
        self.pushButton_21.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.checkBox_2.setText(QCoreApplication.translate("Dialog", u"I want to install Windows 2000\n"
"(depreciated)", None))
        self.pushButton_22.setText(QCoreApplication.translate("Dialog", u"< Previous", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Additional arguments (if needed)", None))
        self.comboBox_17.setItemText(0, QCoreApplication.translate("Dialog", u"pci-ohci", None))
        self.comboBox_17.setItemText(1, QCoreApplication.translate("Dialog", u"piix3-usb-uhci", None))
        self.comboBox_17.setItemText(2, QCoreApplication.translate("Dialog", u"qemu-xhci", None))
        self.comboBox_17.setItemText(3, QCoreApplication.translate("Dialog", u"usb-ehci", None))

        self.checkBox_3.setText(QCoreApplication.translate("Dialog", u"Add USB support", None))
    # retranslateUi

